In [1]:
import csv as csv 
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv("data/train.csv") 
df_test = pd.read_csv("data/test.csv") 

In [3]:
df_train.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
df_train.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [5]:
df_train['AgeFill'] = df_train['Age']
df_test['AgeFill'] = df_test['Age']

In [6]:
df_train['Gender'] = df_train['Sex'].map( {'female': 0, 'male': 1} ).astype(int)
df_test['Gender'] = df_test['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

In [7]:
 df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  AgeFill  Gender  
0  34.5      0      0   330911   7.8292   NaN        Q     34.5       1  
1  47.0      1      0   363272   7.0000   NaN        S     47.0       0  
2  62.0      0      0   240276   9.6875   NaN        Q     62.0       1  
3  27.0      0      0   315154   8.6625   NaN        S     27.0       1  
4  22.0      1      1  3101298  12.2875   NaN        S     22.0       0

In [8]:
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i,j] = df_train[(df_train['Gender'] == i) & \
                              (df_train['Pclass'] == j+1)]['Age'].dropna().median()
 
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

In [10]:
df_train['AgeFill'] = df_train['Age']

In [11]:
median_ages = np.zeros((2,3))
median_ages

for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i,j] = df_test[(df_train['Gender'] == i) & \
                              (df_test['Pclass'] == j+1)]['Age'].dropna().median()
 
median_ages

df_test['AgeFill'] = df_test['Age']

/Users/serena/anaconda/envs/python27/lib/python2.7/site-packages/pandas/core/frame.py:1808: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "DataFrame index.", UserWarning)


In [12]:
for i in range(0, 2):
    for j in range(0, 3):
        df_train.loc[ (df_train.Age.isnull()) & (df_train.Gender == i) & (df_train.Pclass == j+1),\
                'AgeFill'] = median_ages[i,j]
        
for i in range(0, 2):
    for j in range(0, 3):
        df_test.loc[ (df_test.Age.isnull()) & (df_test.Gender == i) & (df_test.Pclass == j+1),\
                'AgeFill'] = median_ages[i,j]

In [13]:
df_test

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [14]:
df_train['AgeIsNull'] = pd.isnull(df_train.Age).astype(int)
df_test['AgeIsNull'] = pd.isnull(df_test.Age).astype(int)

In [15]:
df_train['FamilySize'] = df_train['SibSp'] + df_train['Parch']
df_test['FamilySize'] = df_test['SibSp'] + df_test['Parch']

In [16]:
df_train['Age*Class'] = df_train.AgeFill * df_train.Pclass
df_test['Age*Class'] = df_test.AgeFill * df_test.Pclass

In [17]:
df_train.dtypes[df_train.dtypes.map(lambda x: x=='object')]
df_test.dtypes[df_test.dtypes.map(lambda x: x=='object')]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [18]:
df_train = df_train.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'PassengerId'], axis=1) 
df_test = df_test.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'PassengerId'], axis=1) 

In [19]:
df_train = df_train.drop(['Age'], axis=1)
df_test = df_test.drop(['Age'], axis=1)

In [20]:
df_train = df_train.dropna()
df_test = df_test.dropna()

In [21]:
df_train.head()

Survived  Pclass  SibSp  Parch     Fare  AgeFill  Gender  AgeIsNull  \
0         0       3      1      0   7.2500       22       1          0   
1         1       1      1      0  71.2833       38       0          0   
2         1       3      0      0   7.9250       26       0          0   
3         1       1      1      0  53.1000       35       0          0   
4         0       3      0      0   8.0500       35       1          0   

   FamilySize  Age*Class  
0           1         66  
1           1         38  
2           0         78  
3           1         35  
4           0        105

In [22]:
df_test.head()

Pclass  SibSp  Parch     Fare  AgeFill  Gender  AgeIsNull  FamilySize  \
0       3      0      0   7.8292     34.5       1          0           0   
1       3      1      0   7.0000     47.0       0          0           1   
2       2      0      0   9.6875     62.0       1          0           0   
3       3      0      0   8.6625     27.0       1          0           0   
4       3      1      1  12.2875     22.0       0          0           2   

   Age*Class  
0      103.5  
1      141.0  
2      124.0  
3       81.0  
4       66.0

In [23]:
train_data = df_train.values
train_data

array([[  0.,   3.,   1., ...,   0.,   1.,  66.],
       [  1.,   1.,   1., ...,   0.,   1.,  38.],
       [  1.,   3.,   0., ...,   0.,   0.,  78.],
       ..., 
       [  0.,   3.,   1., ...,   1.,   3.,  72.],
       [  1.,   1.,   0., ...,   0.,   0.,  26.],
       [  0.,   3.,   0., ...,   0.,   0.,  96.]])

In [24]:
test_data = df_test.values
test_data

array([[   3. ,    0. ,    0. , ...,    0. ,    0. ,  103.5],
       [   3. ,    1. ,    0. , ...,    0. ,    1. ,  141. ],
       [   2. ,    0. ,    0. , ...,    0. ,    0. ,  124. ],
       ..., 
       [   3. ,    0. ,    0. , ...,    0. ,    0. ,  115.5],
       [   3. ,    0. ,    0. , ...,    1. ,    0. ,   69. ],
       [   3. ,    1. ,    1. , ...,    1. ,    2. ,   69. ]])

In [25]:
# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 

# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 100)

# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train_data[0::,1::],train_data[0::,0])

# Take the same decision trees and run it on the test data
output = forest.predict(test_data)

In [28]:
seedling=open("results_v2.csv", "wb")
test=open('data/test.csv', 'rU')
forest_Csv = csv.writer(seedling)
test_file_object = csv.reader(test) 
test_file_object.next() # Header control

['PassengerId',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [29]:
i = -1
for row in test_file_object:
    row.insert(0,output[i].astype(np.uint8))
    forest_Csv.writerow(row)
    i += 1
 
test.close()
seedling.close()